version: "3.9"

services:
  redis:
    image: redis:7-alpine
    restart: unless-stopped
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:3.13-management
    restart: unless-stopped
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASS}
    ports:
      - "5672:5672"
      - "15672:15672"

  celery_worker:
    build:
      context: ..
      dockerfile: Dockerfile
    restart: unless-stopped
    command: celery -A app.celery.celery_app worker --loglevel=info --concurrency=2
    depends_on:
      - redis
      - rabbitmq
    env_file:
      - .env.worker
    environment:
      CELERY_BROKER_URL: amqp://${RABBITMQ_USER}:${RABBITMQ_PASS}@rabbitmq:5672//
      CELERY_RESULT_BACKEND: redis://redis:6379/1
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_DB: 0
