"""empty message

Revision ID: 4e69bd3b348e
Revises: e1708bc93848
Create Date: 2025-11-22 17:15:22.732492

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e69bd3b348e'
down_revision: Union[str, Sequence[str], None] = 'e1708bc93848'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('invalid_reply_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'invalid_reply_count')
    # ### end Alembic commands ###
