"""added column 'message_id' in relation 'User'

Revision ID: e33b50665534
Revises: 66094dc9d5de
Create Date: 2025-11-22 15:09:59.647737

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e33b50665534'
down_revision: Union[str, Sequence[str], None] = '66094dc9d5de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('message_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'message_id')
    # ### end Alembic commands ###
